name: CodeStyle Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    name: CodeStyle Check (Python ${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
